import "@/styles/globals.css";
import {cn} from "@/lib/utils";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={cn("font-rig-sans")}>{children}</body>
        </html>
    )
}

