import "@/styles/globals.css";
import {cn} from "@/lib/utils";
import Providers from "@/components/context/providers/providers";
import {ReactNode} from "react";


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body className={cn("font-rig-sans")}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}

